//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class grading_devEntities : DbContext
    {
        public grading_devEntities()
            : base("name=grading_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_WAFER_RESUME_HIS> TBL_WAFER_RESUME_HIS { get; set; }
        public virtual DbSet<TBL_WAFER_RESUME> TBL_WAFER_RESUME { get; set; }
        public virtual DbSet<TBL_WAFER_RESUME_ITEM> TBL_WAFER_RESUME_ITEM { get; set; }
        public virtual DbSet<TBL_WAFER_TXN_LOG> TBL_WAFER_TXN_LOG { get; set; }
        public virtual DbSet<TBL_PRODUCT_INFO> TBL_PRODUCT_INFO { get; set; }
        public virtual DbSet<TBL_WAFER_RESUME_LOOKUP> TBL_WAFER_RESUME_LOOKUP { get; set; }
        public virtual DbSet<TBL_SHIPLOGIC_CONFIG> TBL_SHIPLOGIC_CONFIG { get; set; }
        public virtual DbSet<TBL_WAFER_RESUME_VIEW> TBL_WAFER_RESUME_VIEW { get; set; }
    }
}
