//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WAFER_RESUME_VIEW
    {
        public System.Guid Id { get; set; }
        public string HeaderLevel { get; set; }
        public string HeaderType { get; set; }
        public string Wafer_Id { get; set; }
        public string RW_Wafer_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime HeaderCreation_Date { get; set; }
        public System.DateTime HeaderLast_Updated_Date { get; set; }
        public string HeaderAttribute1 { get; set; }
        public string HeaderAttribute2 { get; set; }
        public string ItemType { get; set; }
        public string ItemKey { get; set; }
        public string ItemValue { get; set; }
        public int ItemStatus { get; set; }
        public string ItemAttribute1 { get; set; }
        public System.Guid Header_Id { get; set; }
    }
}
