//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bin_code_file_status
    {
        public int Id { get; set; }
        public string App_Mode { get; set; }
        public string File_Type { get; set; }
        public string wafer_id { get; set; }
        public string rw_wafer_id { get; set; }
        public string epi_type { get; set; }
        public string File_path { get; set; }
        public string result_path { get; set; }
        public Nullable<bool> is_Valid { get; set; }
        public Nullable<bool> is_Completed { get; set; }
        public string error_message { get; set; }
        public Nullable<System.DateTime> loaded_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
