//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WAFER_RESUME_ITEM
    {
        public System.Guid Id { get; set; }
        public System.Guid Header_Id { get; set; }
        public string Type { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public string Attribute1 { get; set; }
    }
}
