//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_serial_wat_history
    {
        public int Id { get; set; }
        public string wafer_id { get; set; }
        public string filename { get; set; }
        public Nullable<System.DateTime> loaded_date { get; set; }
        public string dispo_date { get; set; }
        public string part_id { get; set; }
        public string fab_wafer_id { get; set; }
        public string disposition_code { get; set; }
        public string remap_required { get; set; }
        public string test_result { get; set; }
        public string bin_three { get; set; }
        public string comment { get; set; }
        public string source_date { get; set; }
        public string loaded_month { get; set; }
        public Nullable<System.DateTime> history_insertion_date { get; set; }
        public string history_type { get; set; }
        public string update_by { get; set; }
        public string wait_released { get; set; }
        public string iqe_bouleid { get; set; }
        public string epi_reactor { get; set; }
        public Nullable<System.DateTime> insertion_date { get; set; }
        public string source_table { get; set; }
        public string line_number { get; set; }
        public string die_count { get; set; }
        public string spec_failure { get; set; }
        public string drift_failure { get; set; }
        public string t0_avg_nf__dppm_ { get; set; }
        public string post_bi_avg_nf__dppm_ { get; set; }
        public string post_wat_avg_nf__dppm_ { get; set; }
        public string shippable_zone__dppm_ { get; set; }
        public string exclusion_zone__dppm_ { get; set; }
        public string t0_max_nf____worst_die_ { get; set; }
        public string post_bi_max_nf____worst_die_ { get; set; }
        public string post_wat_max_nf____worst_die_ { get; set; }
        public string max_po_drift_post_wat__w_ { get; set; }
        public string avg_po_drift_post_wat__w_ { get; set; }
        public string min_po_drift_post_wat__w_ { get; set; }
        public string max_vf_drift_post_wat__v_ { get; set; }
        public string avg_vf_drift_post_wat__v_ { get; set; }
        public string min_vf_drift_post_wat__v_ { get; set; }
        public string max_na_drift_post_wat { get; set; }
        public string avg_na_drift_post_wat { get; set; }
        public string min_na_drift_post_wat { get; set; }
        public string dead_emitter_map_radar_ref { get; set; }
        public string max_wl_l_drift_post_wat__nm_ { get; set; }
        public string avg_wl_l_drift_post_wat__nm_ { get; set; }
        public string min_wl_l_drift_post_wat__nm_ { get; set; }
        public string max_wl_r_drift_post_wat__nm_ { get; set; }
        public string avg_wl_r_drift_post_wat__nm_ { get; set; }
        public string min_wl_r_drift_post_wat__nm_ { get; set; }
        public string t0_neighbor_failures____ { get; set; }
        public string post_bi_neighbor_failures____ { get; set; }
        public string post_wat_neighbor_failures____ { get; set; }
        public string max_wl_drift_post_wat__nm_ { get; set; }
        public string avg_wl_drift_post_wat__nm_ { get; set; }
        public string min_wl_drift_post_wat__nm_ { get; set; }
        public string max_w0_drift_post_wat { get; set; }
        public string avg_w0_drift_post_wat { get; set; }
        public string min_w0_drift_post_wat { get; set; }
        public string max_dense_uni_drift_post_wat { get; set; }
        public string max_sparse_uni_drift_post_wat { get; set; }
        public string Failure { get; set; }
        public string Final_Grading_Result_Remark { get; set; }
        public string max_T0_CBP_r_post_wat { get; set; }
        public string avg_T0_CBP_r_post_wat { get; set; }
        public string min_T0_CBP_r_post_wat { get; set; }
        public string max_T0_CBP_a_post_wat { get; set; }
        public string avg_T0_CBP_a_post_wat { get; set; }
        public string min_T0_CBP_a_post_wat { get; set; }
        public string max_T0_CBP_q_post_wat { get; set; }
        public string avg_T0_CBP_q_post_wat { get; set; }
        public string min_T0_CBP_q_post_wat { get; set; }
        public string max_Te_CBP_r_post_wat { get; set; }
        public string avg_Te_CBP_r_post_wat { get; set; }
        public string min_Te_CBP_r_post_wat { get; set; }
        public string max_Te_CBP_a_post_wat { get; set; }
        public string avg_Te_CBP_a_post_wat { get; set; }
        public string min_Te_CBP_a_post_wat { get; set; }
        public string max_Te_CBP_q_post_wat { get; set; }
        public string avg_Te_CBP_q_post_wat { get; set; }
        public string min_Te_CBP_q_post_wat { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string epi_type { get; set; }
    }
}
