//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WAFER_RESUME_HIS
    {
        public System.Guid Id { get; set; }
        public string TXN_Type { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Wafer_Id { get; set; }
        public string RW_Wafer_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Created_By { get; set; }
        public string LastUpdated_By { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public Nullable<System.DateTime> Sys_Updated_Date { get; set; }
    }
}
