//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumMVC_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WAFER_TXN_LOG
    {
        public System.Guid Id { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
        public string Wafer_Id { get; set; }
        public string RW_Wafer_Id { get; set; }
        public string Log { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public string Created_By { get; set; }
    }
}
